### ISSUE TITLE
Doesn't work with Command Line app

### ISSUE THREAD

**Issue by adamtomecek** [philiphardy/ID3Edit#3]
Hi,

I've spent hours to get this framework work in my command line tool app, but after running I always get the error

```
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/myuser/Library/Developer/Xcode/DerivedData/CurseMusic-bmydwpowdnnuweasqqlrmaieaexr/Build/Products/Debug/ID3Edit.framework/Versions/A/ID3Edit
  Reason: image not found
```

I'm guessing this is related to your framework project if I'm correct. Any idea what to do?

**Comment by philiphardy** [comment]
Hey sorry for the late response.

Frameworks are tricky with Command Line Tools, however, I did get it working.

So as the error message indicates, it cannot find the swift libraries. To fix this, you can manually add the directory to these in the Runpath Search Path under Project Settings > Build Settings > Linking.

For me, this directory is located at:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx
