### ISSUE TITLE
Update Swift 3

### ISSUE THREAD

**Issue by larrybg** [philiphardy/ID3Edit#7]
Hi Philip,
Are you planning to update ID3Edit framework to Swift 3? I've just updated my code and errors are coming only from the framework. Wondering if you've already done some work on that.
Can you please share your plans on release schedules?

Update: I've started the migration to Swift 3 and down to 8 errors that I have no clue how to resolve. Digging into internet and articles but so far nothing. The errors that I'm stuck with mostly "UnsafePointer<Byte>" - "Cannot invoke initializer for type 'UnsafePointer<TagParser.Byte>' with an argument list of type '(UnsafeRawPointer)' ... Any idea?

**Comment by ryanfrancesconi** [comment]
I'm also interested to see this update. I've already adapted what I needed for my project to Swift 3, but it was based off the original ID3Edit and it only parses v3 tags - doesn't write them. I had finished that before Philip released his own v3 update, so it is somewhat different. Classes are attached if they are of any use. Incomplete - but will run under swift 3.

[ID3v2.zip](https://github.com/philiphardy/ID3Edit/files/554472/ID3v2.zip)

**Comment by waldimarow** [comment]
Hey,
I recently needed a ID3 editor tool for my project. Since I was using Swift 3.0 I have ported the original ID3Edit to swift 3. So If you are interested, I have a fork that works with the current swift version.

**Comment by melMass** [comment]
@TheBelarussian I can't seem to make it work under Swift 3 is your fork broken ?

**Comment by waldimarow** [comment]
@melMass it worked for me, if you could send me the error, I would look into it.

**Comment by larrybg** [comment]
Hey,
Did anyone had a chance to convert ID3v3 to Swift 3? And I'm talking about real conversion - replacing NSData wth Data and etc.
Philiphardy, hey man! Just couple hours of your time to convert it to Swift 3 will make lots of people happy! ;-)

**Comment by mouness2020** [comment]
me too please update it to swift 3 man  👍

**Comment by philiphardy** [comment]
Sorry for such a late response, all my time has been absorbed by studies as I prepare to graduate. 

Due to the lack of backwards compatibility and versioning issues that comes with Swift, I will soon be recreating this framework in Objective-C. This should create a stable framework that should not have to be reworked every time a new Swift version is released. Objective-C frameworks work within Swift frameworks so no worries there!

If anyone wants to contribute, I will gladly accept a helping hand.

**Comment by philiphardy** [comment]
I shouldn't have closed this project has been converted.

**Comment by ryanfrancesconi** [comment]
I think the biggest change was the Swift 3 update - Apple had to break a bunch of stuff for that, but I'd expect it to be more stable moving forward with less versioning changes. I think leaving your framework in Swift is actually a wiser decision overall.

**Comment by larrybg** [comment]
Agree with @ryanfrancesconi - it's better to leave it in Swift. Some maintenance will be required but convert everything to Objective-C is lots of work.

**Comment by philiphardy** [comment]
I appreciate your concern. However, this isn't the first time I had to change everything due to Swift changing. I will leave the both the Objective C and Swift versions up for people to use. Please let me know if you find an issue.
