### ISSUE TITLE
Null Terminators in tags

### ISSUE THREAD

**Issue by daeljan** [philiphardy/ID3Edit#9]
using Xcode 7.3.1

debugPrint("Title:\t\(mp3File.getTitle())")
debugPrint("Artist:\t\(mp3File.getArtist())")
debugPrint("Album:\t\(mp3File.getAlbum())")
debugPrint("Lyrics:\n\(mp3File.getLyrics())")

This outputs:

"Title:\t\0I Ran\0"
"Artist:\t\0A Flock Of Seagulls\0"
"Album:\t\0The Best of A Flock of Seagulls\0"
"Lyrics:\n"

Trying to display these strings on a GUI doesn't work unless I call something like:

let title = mp3File.getTitle().stringByTrimmingCharactersInSet(NSCharacterSet.controlCharacterSet())

...which returns the string with the null terminators trimmed off.
Excuse the taste in music, and thanks for creating this library - it is really useful. If I can add any more context to this problem please do let me know.

**Comment by philiphardy** [comment]
I'm sorry about this. I'll fix this issue in the next version which will be out soon.

**Comment by philiphardy** [comment]
I believe this issue is fixed. Please let me know if not.
